### ISSUE TITLE
Configuring shellcheck arguments

### ISSUE THREAD

**Issue by jackm** [detailyang/pre-commit-shell#7]
Is there a method for passing arguments to shellcheck when it is invoked?

For example, if I wanted to pass the [`-x` argument to shellcheck](https://github.com/koalaman/shellcheck/wiki/Integration#decide-whether-you-want-to-follow-sourced-files-that-are-not-specified-as-input) is there a way to do that in the .pre-commit-config.yaml file?

Aside from forking this repo and making the change in entry point, the only other option I see is to set the `SHELLCHECK_OPTS` environment variable.

**Comment by detailyang** [comment]
Hello
@jackm 

Sorry to reply. I found the pre-commit framework support the args as the following:

````yaml
-   repo: git://github.com/detailyang/pre-commit-shell
    sha: aa5b670d06cbc74881529b4e241a130a2cacd153
    hooks:
    - id: shell-lint
      args: [--format=json]
````
